### ISSUE TITLE
Migration chance from react-native-router-flux or 4.0 beta?? 

### ISSUE THREAD

**Issue by iiitmahesh** [mcnamee/react-native-starter-kit#101]
Migration chance from react-native-router-flux or 4.0 beta??

**Comment by aksonov** [comment]
Just finished some basic conversion (without dynamic recipes retrieval from firebase) to RNRF v4: https://github.com/aksonov/react-native-starter-app

Sorry, Redux was replaced for Mobx for great simplicity...

**Comment by mcnamee** [comment]
Hi @iiitmahesh  The latest major release now has RNRF v4.

Thanks @aksonov for your work!
