### ISSUE TITLE
Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

### ISSUE THREAD

**Issue by caciobanita** [mcnamee/react-native-starter-kit#102]
### Help us reproduce - tell us about your environment

1. Mac and Windows
1. Ios and Android

### Steps to reproduce

1. I use Action and reducer for change the state of my app. After i call the function from my componet to run the action, if i press the back button i get this worning "an only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component."
1.
1.

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by mcnamee** [comment]
Sorry @caciobanita - we probably need a bit more info - maybe code snippet/s.

In general, that error occurs when you're setting state on a component that isn't in focus. Eg. perhaps you've navigated to a second screen and you try and change state on the previous component. Or you set a timeout which hasn't executed yet, and you navigate to another screen, then the timeout executes on that previous screen.
