### ISSUE TITLE
Init Setup don`t worked

### ISSUE THREAD

**Issue by gHashTag** [mcnamee/react-native-starter-kit#104]
### Help us reproduce - tell us about your environment

1. Mac. iOS. Latest version

### Steps to reproduce

1. Has connected all instructions

### Expected result

1. I see an activating indicator and this sentence is worth
2. SocketRocket: In debug mode.  Allowing connection to any root cert

### Actual result

1. [Screenshot, logs]
![2017-08-24 21 53 52](https://user-images.githubusercontent.com/6774813/29683393-e6f27c6c-8916-11e7-896b-10166b151c1d.png)

**Comment by mcnamee** [comment]
Sorry @gHashTag I haven't actually seen this before.

Anyone else?

**Comment by shic** [comment]
I have seen this. Maybe ViewStylePropTypes must be used now.

**Comment by mcnamee** [comment]
Sorry no one's been able to suggest a solution @gHashTag 

I'll close this one, but if you did find a solution - it'd be awesome if you commented back here to help others.
