### ISSUE TITLE
Got “Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView” error  when run Android <=4.4, but works on Android > 4.4

### ISSUE THREAD

**Issue by shic** [mcnamee/react-native-starter-kit#110]
When I run on Android <=4.4, got the following error,  but works on Android > 4.4:

 Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

![image](https://user-images.githubusercontent.com/4471626/31048402-b4f9693c-a61c-11e7-8814-94b2cd577de4.png)

Searched on Internet, maybe the problem is this project used some library that cause this error. But do not know which one.

**Comment by shic** [comment]
Someone has idea of this? For me this is a compatibility bug.

**Comment by mcnamee** [comment]
React Native says it supports >= Android 4.1. However I wonder if the minor version has slowly increased as new RN features have been added and the docs haven't been updated(?)

**Comment by shic** [comment]
Anyway when I run on Android <=4.4, got errors. Does anyone confirm this?

**Comment by carlosagil** [comment]
@shic error when passing and run (Android <=4.4) both borderRadius AND backgroundColor to a <Button><Card> in this case.

`

// src/components/ui/Button.js
...  
buttonProps = () => {
    // Defaults
    const props = {
      title: 'Coming Soon...',
      color: '#fff',
      fontWeight: 'bold',
      onPress: this.props.onPress,
      fontFamily: AppFonts.base.family,
      fontSize: AppFonts.base.size,
      // borderRadius: AppSizes.borderRadius,          **<- Removing this prop**
      raised: true,
...

// src/components/ui/Card.js
...
  cardProps = () => {
    // Defaults
    const props = {
      dividerStyle: [{
        backgroundColor: AppColors.border,
      }],
      ...this.props,
      containerStyle: [{
        backgroundColor: AppColors.cardBackground,
        // borderRadius: AppSizes.borderRadius,  **<- Removing this prop**
        borderColor: AppColors.border
...


const styles = StyleSheet.create({
  button: {
    borderRadius: AppSizes.borderRadius,  // **<- And adding the style here seems to resolve the issue**
  },

`

**Comment by mcnamee** [comment]
Sorry no one's been able to find a solution for you @shic 

I'll close this one, but if you did find a solution - it'd be awesome if you commented back here to help others.
