### ISSUE TITLE
Firebase is not connected correctly

### ISSUE THREAD

**Issue by vipinlahoti** [mcnamee/react-native-starter-kit#119]
Environment: Mac - ios
firebase credentials are added correctly but still im getting an error as "Firebase is not connected correctly".

**Comment by kxxoling** [comment]
I have the same issue while configured like this:

![image](https://user-images.githubusercontent.com/1227139/32788275-6530e694-c91e-11e7-836c-d4f0c2f989a0.png)

Bucket and MESSAGING_SENDER_ID cannot be freely used so I left them to be null.

BTW, how can I remove the whole firebase part from this project? Firebase is not reachable in my country.

**Comment by eddOrnelas** [comment]
Look like the node module react-native-dotenv is not working properly, i recomend hardcode the firebase credentials on /src/constants/firebase.js
Comment the line:

```
/*import {
  API_KEY,
  AUTH_DOMAIN,
  DATABASE_URL,
  STORAGE_BUCKET,
  MESSAGING_SENDER_ID,
} from 'react-native-dotenv';*/
```

and add your own constants:

`const API_KEY = '*****';
const AUTH_DOMAIN = '*****';
const DATABASE_URL = '*****';
const STORAGE_BUCKET = '*****';
const MESSAGING_SENDER_ID = '*****';
`

**Comment by mcnamee** [comment]
Good suggestion @eddOrnelas 
Lots of people were having issues with `react-native-dotenv` so it's been removed in the latest major release.
