### ISSUE TITLE
Can navigate from native screen to particular scene in react native?

### ISSUE THREAD

**Issue by brainahdev** [mcnamee/react-native-starter-kit#122]
Moving from react native scene to native is possible but how to navigate from native screen to particular scene in react native?

For example from Scene A (React Native) I am navigating to Screen B (Native Screen). I need to navigate from Screen B (Native Screen) to Scene C (React Native)

**Comment by mcnamee** [comment]
Sorry no one's been able to suggest a solution @brainahdev 
I'll close this one, but if you did find a solution - it'd be awesome if you commented back here to help others.

**Comment by brainahdev** [comment]
For now I plan to use deep linking concept for that kind of navigation..if still any one comes with better or right solution that would be great.
