### ISSUE TITLE
The react-native-google-analytics-bridge seems corrupted

### ISSUE THREAD

**Issue by joeydh** [mcnamee/react-native-starter-kit#124]
The react-native-google-analytics-bridge seems corrupted

1. Windows 10
2. All versions the same due to NPM
3. NodeJS 8.9.1 
4. Master branche of react-native-starter-app

### Expected result
The program should run. 

### Actual result

I can't seem to find a solution it seems it's looking for stuff that  does not exist

###
"C:\Program Files\nodejs\node.exe" C:\Users\Joey\AppData\Roaming\npm\node_modules\react-native-cli run-android --no-packager
Scanning 684 folders for symlinks in C:\Users\Joey\WebstormProjects\react-native-boa\node_modules (30ms)
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-google-analytics-bridge:compileLint
:react-native-google-analytics-bridge:copyReleaseLint UP-TO-DATE
:react-native-google-analytics-bridge:preBuild UP-TO-DATE
:react-native-google-analytics-bridge:preReleaseBuild UP-TO-DATE
:react-native-google-analytics-bridge:checkReleaseManifest
:react-native-google-analytics-bridge:preDebugAndroidTestBuild UP-TO-DATE
:react-native-google-analytics-bridge:preDebugBuild UP-TO-DATE
:react-native-google-analytics-bridge:preDebugUnitTestBuild UP-TO-DATE
:react-native-google-analytics-bridge:preReleaseUnitTestBuild UP-TO-DATE
:react-native-google-analytics-bridge:prepareComAndroidSupportAppcompatV72301Library
:react-native-google-analytics-bridge:prepareComAndroidSupportSupportCompat2520Library
:react-native-google-analytics-bridge:prepareComAndroidSupportSupportCoreUi2520Library
:react-native-google-analytics-bridge:prepareComAndroidSupportSupportCoreUtils2520Library
:react-native-google-analytics-bridge:prepareComAndroidSupportSupportFragment2520Library
:react-native-google-analytics-bridge:prepareComAndroidSupportSupportMediaCompat2520Library
:react-native-google-analytics-bridge:prepareComAndroidSupportSupportV42520Library
:react-native-google-analytics-bridge:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:react-native-google-analytics-bridge:prepareComFacebookFrescoDrawee101Library
:react-native-google-analytics-bridge:prepareComFacebookFrescoFbcore101Library
:react-native-google-analytics-bridge:prepareComFacebookFrescoFresco101Library
:react-native-google-analytics-bridge:prepareComFacebookFrescoImagepipeline101Library
:react-native-google-analytics-bridge:prepareComFacebookFrescoImagepipelineBase101Library
:react-native-google-analytics-bridge:prepareComFacebookFrescoImagepipelineOkhttp3101Library
:react-native-google-analytics-bridge:prepareComFacebookReactReactNative0443Library
:react-native-google-analytics-bridge:prepareComFacebookSoloaderSoloader010Library
:react-native-google-analytics-bridge:prepareComGoogleAndroidGmsPlayServicesAnalytics1104Library
:react-native-google-analytics-bridge:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1104Library
:react-native-google-analytics-bridge:prepareComGoogleAndroidGmsPlayServicesBase1104Library
:react-native-google-analytics-bridge:prepareComGoogleAndroidGmsPlayServicesBasement1104Library
:react-native-google-analytics-bridge:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1104Library
:react-native-google-analytics-bridge:prepareComGoogleAndroidGmsPlayServicesTasks1104Library
:react-native-google-analytics-bridge:prepareOrgWebkitAndroidJscR174650Library
:react-native-google-analytics-bridge:prepareReleaseDependencies
:react-native-google-analytics-bridge:compileReleaseAidl
:react-native-google-analytics-bridge:compileReleaseRenderscript
:react-native-google-analytics-bridge:generateReleaseBuildConfig
:react-native-google-analytics-bridge:generateReleaseAssets UP-TO-DATE
:react-native-google-analytics-bridge:mergeReleaseAssets
:react-native-google-analytics-bridge:generateReleaseResValues
:react-native-google-analytics-bridge:generateReleaseResources
:react-native-google-analytics-bridge:mergeReleaseResourcesAAPT out(859030704) : No Delegate set : lost message:Done
AAPT out(1742668597) : No Delegate set : lost message:Done
AAPT out(859030704) : No Delegate set : lost message:Done
AAPT out(1063839377) : No Delegate set : lost message:Done
AAPT out(1443316408) : No Delegate set : lost message:Done
AAPT out(990501810) : No Delegate set : lost message:Done
AAPT out(1443316408) : No Delegate set : lost message:Done
AAPT out(954880517) : No Delegate set : lost message:Done
AAPT out(1303490061) : No Delegate set : lost message:Done
AAPT out(505623693) : No Delegate set : lost message:Done
AAPT out(72667516) : No Delegate set : lost message:Done
AAPT out(2000344939) : No Delegate set : lost message:Done
AAPT out(2000344939) : No Delegate set : lost message:Done
AAPT out(990501810) : No Delegate set : lost message:Done
AAPT out(851920987) : No Delegate set : lost message:Done
AAPT out(718751170) : No Delegate set : lost message:Done
AAPT err(851920987): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-hdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(718751170): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-hdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1063839377): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(72667516): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-mdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1303490061): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(2000344939): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(2000344939): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xhdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(954880517): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1443316408): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-mdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1443316408): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xxhdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(990501810): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xhdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(990501810): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-hdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(1742668597): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(505623693): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xxhdpi-v4\common_google_signin_btn_text_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(859030704): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png ERROR: Unable to open PNG file
AAPT err(859030704): C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-mdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png ERROR: Unable to open PNG file

:react-native-google-analytics-bridge:processReleaseManifest
:react-native-google-analytics-bridge:processReleaseResources FAILED
C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable\common_google_signin_btn_icon_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal_background').
C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable\common_google_signin_btn_icon_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal_background').
C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable\common_google_signin_btn_text_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal_background').
C:\Users\Joey\WebstormProjects\react-native-boa\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable\common_google_signin_btn_text_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal_background').

BUILD FAILED
FAILURE: Build failed with an exception.

Total time: 26.995 secs
* What went wrong:
Execution failed for task ':react-native-google-analytics-bridge:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\Android\Sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by joeydh** [comment]
Couldn't find a fix other than removing the feature

**Comment by mcnamee** [comment]
It seems that there was an issue with the react-native-google-analytics-bridge package.
It's been removed in the latest major release.

Thanks for reporting and suggesting solutions
