### ISSUE TITLE
ld: library not found for -lRNDeviceInfo

### ISSUE THREAD

**Issue by beratuslu** [mcnamee/react-native-starter-kit#126]
Hello guys, 

I am doing exactly what document says, when I try to start project from XCode it build fails:
I am gonna kill my self, I cant figure out what it is:

![image](https://user-images.githubusercontent.com/94031/34341578-369ee846-e9ab-11e7-84b3-a5221b87f138.png)

**Comment by cnhuye** [comment]
I'm looking for answer for the same error .
![image](https://user-images.githubusercontent.com/486552/34343590-429534c4-ea10-11e7-9118-4ee1728cbe32.png)

**Comment by guizmo** [comment]
ok this won't help... but i had this error and using my google powers i
fixed it... but cannot remember how... maybe cocoapods issue... not sure.

**Comment by cnhuye** [comment]
I solved this error by adding "react-native-device-info" in package.json "dependencies" section:

"dependencies": {
   ...
    "react-native-device-info": "^0.10.1"

  }

**Comment by Gabswim** [comment]
yes I had the same problem and I fixed it like @cnhuye  by adding https://yarnpkg.com/en/package/react-native-device-info. We should do a pull request for it.

**Comment by mcnamee** [comment]
Sorry guys my fault - there was a [pull request to fix that which has been merged](https://github.com/mcnamee/react-native-starter-kit/commit/417e36cfe1097c85734440057da74a3761968372).

This also isn't an issue in the latest major version release, so I'll close this one.

Thanks for reporting and proposing solutions @Gabswim @cnhuye @guizmo @beratuslu !
