### ISSUE TITLE
Error fontFamily Roboto on Android 

### ISSUE THREAD

**Issue by yovierayz** [mcnamee/react-native-starter-kit#129]
I have problem when running on android, running well on ios and web. Is this normal or i missing something?

error message :

console.error: "fontFamily 'Roboto_medium' is not a system font and has not been loaded through Expo.Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Expo.Font.loadAsync."
newConsoleFunc
    Logs.js:190:21
error
    YellowBox.js:69:16
processFontFamily
    Font.js:36:10
diffProperties
    ReactNativeFiber-dev.js:2939:112
addProperties
    ReactNativeFiber-dev.js:2950:30
addNestedProperty
    ReactNativeFiber-dev.js:2916:59
diffNestedProperty
    ReactNativeFiber-dev.js:2912:613
diffProperties
    ReactNativeFiber-dev.js:2941:91
addProperties
    ReactNativeFiber-dev.js:2950:30
create
    ReactNativeFiber-dev.js:2957:33
createInstance
    ReactNativeFiber-dev.js:3114:69
completeWork
    ReactNativeFiber-dev.js:1965:55
completeUnitOfWork
    ReactNativeFiber-dev.js:2548:76
performUnitOfWork
    ReactNativeFiber-dev.js:2571:56
workLoop
    ReactNativeFiber-dev.js:2595:141
_invokeGuardedCallback
    ReactNativeFiber-dev.js:75:23
invokeGuardedCallback
    ReactNativeFiber-dev.js:49:40
performWork
    ReactNativeFiber-dev.js:2634:41
scheduleUpdateImpl
    ReactNativeFiber-dev.js:2768:101
scheduleUpdate
    ReactNativeFiber-dev.js:2751:38
enqueueSetState
    ReactNativeFiber-dev.js:1569:90
setState
    react.development.js:237:31
handlePersistorState
    react.js:43:25
dispatch
    createStore.js:186:6
rehydrate
    persistStore.js:99:23
<unknown>
    persistReducer.js:76:27
tryCallOne
    core.js:37:14
<unknown>
    core.js:123:25
<unknown>
    JSTimers.js:295:23
_callTimer
    JSTimers.js:148:6
_callImmediatesPass
    JSTimers.js:196:17
callImmediates
    JSTimers.js:464:11
__callImmediates
    MessageQueue.js:282:4
<unknown>
    MessageQueue.js:137:6
__guard
    MessageQueue.js:269:6
flushedQueue
    MessageQueue.js:136:17
invokeCallbackAndReturnFlushedQueue
    MessageQueue.js:132:11

**Comment by mcnamee** [comment]
Hi there,
I don't experience that one myself, but it looks to be an Expo and/or Native Base related issue.

Would you be able to look into those repos and let us know here, how you go?

**Comment by yovierayz** [comment]
I just clone from this repository, and following instruction in readme doc. My friend has same problem with me.
I think the issue came from expo, but you say don't experience issue like that.
So if you have no problem, I should not too.

**Comment by mcnamee** [comment]
Hey @yovierayz 
You're right, thanks for raising the issue. When debugging locally (compared to viewing the public Expo version) the error appears. I've just pushed some code which removes the Roboto_medium font reference and resolves.

Can you have a quick test and let us know?

**Comment by cidicles** [comment]
This fixed it for me! Thanks!

**Comment by yovierayz** [comment]
Hi @mcnamee , the issues has been gone!
Thanks :)

**Comment by kigawas** [comment]
https://github.com/GeekyAnts/NativeBase/issues/1240

Here is a solution

**Comment by DaggieBlanqx** [comment]
> [GeekyAnts/NativeBase#1240](https://github.com/GeekyAnts/NativeBase/issues/1240)
> 
> Here is a solution

After searching for tonnes of solutions , this worked for me , thank you

**Comment by bearkfear** [comment]
Hey, it's works for me. Just put a conditional if is loading and change to false when is done.

**Comment by josepaez2** [comment]
Based on achums007 commented on 24 Apr 2018,

https://stackoverflow.com/questions/57066075/console-error-fontfamily-roboto-medium-is-not-a-system-font-and-has-not-been

import React, { Component } from 'react';
import { View, } from "react-native";
import { Button, Text } from 'native-base';

export default class MyComponent extends Component {

  state = {
    loading: true
  }

  async componentDidMount() {
    await Font.loadAsync({
      'Roboto': require('native-base/Fonts/Roboto.ttf'),
      'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
      ...Ionicons.font,
    })
    this.setState({ loading: false })
  }

  render() {
       if (this.state.loading) {
         return (
           <View></View>
         );
       }
        return (
                 <View>
                     <Button>
                       <Text>Click me!</Text>
                     </Button>
                  </View>
                )
   }
}
