### ISSUE TITLE
Question: Updating the App Icon

### ISSUE THREAD

**Issue by dwmkerr** [mcnamee/react-native-starter-kit#130]
Hi @mcnamee, thanks for sharing such a great starter kit! I've been enjoying following the updates over the last few weeks as things get re-written.

I was wondering if you'd be interested in a PR for managing the app icon. I have a tool called [app-icon](https://github.com/dwmkerr/app-icon) which let's you add an `icon.png` at your project root, then just run `npx app-icon generate` (or install globally and run `npm app-icon generate`).

I think this might be a nice thing to add to the docs as for many people who use this to start their own projects, one of the first things they'll want to do is add their own icon.

What do you think? I thought I'd before creating the PR as it might seem self-serving to suggest my own project, I certainly find it useful, if you think others would too let me know and I'll do a PR on the docs.

Cheers!

Dave

**Comment by mcnamee** [comment]
Great suggestion! Thanks for bringing it up. 

Can you please double check before submitting a pull request: does Expo's built in tools already cover what you're suggesting? 

https://docs.expo.io/versions/latest/guides/configuration.html#icon

**Comment by dwmkerr** [comment]
Hi @mcnamee - looking into it, the `icon` in the `app.json` will control the icon within expo only, meaning that at the point when the user decides to create a standalone app they'll get the default xcode/android icons. If they already have an icon file in their project to set the expo icon, it'll be easy to use this to generate the native icons.

So it looks like `icon` will work in expo only - do you have a specific place in the docs you think would be good to describe steps like this for customising the app? I remember in the older version there was a section on renaming, maybe somewhere similar?

**Comment by mcnamee** [comment]
Thanks for looking into it @dwmkerr 

Great findings. I'd suggest implementing the [app-icon](https://github.com/dwmkerr/app-icon) package and add some basic docs (linking to the main repo's docs) in the [FAQs doc](/mcnamee/react-native-starter-kit/blob/master/docs/faqs.md).

Thanks Dave!

**Comment by dwmkerr** [comment]
Hi @mcnamee sorry for the delay! I opened a PR, OK to take a look? #135?
