### ISSUE TITLE
Question : How to move tabbar in android to bottom

### ISSUE THREAD

**Issue by yovierayz** [mcnamee/react-native-starter-kit#132]
Hi @mcnamee , sorry i want to ask you again.
I try to search in native-base-theme/variables/platform.js but i don't find any code related to determine the position of the tab for ios or android. Previously in v2.x.x you just using scene with custom style in theme folder, but in v3 using Tabs from react-native-router-flux, i've never used it.
Can you tell me, which file should i change to move tabs from top to bottom in android like ios? Because i want to add drawer for this new starter kit.
Thanks man!

**Comment by mcnamee** [comment]
Hi there, 
Please see the [react-native-router-flux API docs](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#tabs-tabs-or-scene-tabs). Specifically **tabBarPosition** under **Tabs**

**Comment by yovierayz** [comment]
Hi @mcnamee ,
I just adding property tabBarPosition : 'bottom' in navigation.js and it works!
Thank you very much!
