### ISSUE TITLE
 Question: How can add firebase message to push notification

### ISSUE THREAD

**Issue by Tan-nn** [mcnamee/react-native-starter-kit#133]
Hi @mcnamee,
Can you guide me how can add FCM to push notification on Android and IOS

Thanks for sharing such a great starter kit!

**Comment by mcnamee** [comment]
I'll leave this issue open for a couple of weeks in case others can/want to provide help.

But I'd suggest starting with the [FCM docs](https://firebase.google.com/docs/cloud-messaging/).
