### ISSUE TITLE
The Expo Demo is update? and there's support for "Firebase social auth"?

### ISSUE THREAD

**Issue by MichelDiz** [mcnamee/react-native-starter-kit#134]
Are just this questions. I opened the Expo Demo and doesn't explains visually/logically explicit this.

cheers

**Comment by mcnamee** [comment]
Hi @MichelDiz 
No there's nothing built into this project for Firebase Social Auth. Whilst this feature might be used for some, I'm not keen on tying the boilerplate too tightly to a single service like Firebase.
