### ISSUE TITLE
Getting error while trying to login

### ISSUE THREAD

**Issue by pranavpr** [mcnamee/react-native-starter-kit#136]
### Help us reproduce - tell us about your environment

1. Mac, expo

### Steps to reproduce

1. Clone the repository
2. Start app and open in expo
3. Go to login page and try to login

### Expected result

1. It should open the home page

### Actual result

1. Page remains at login page. Following error is shown in console:
`Error: TypeError: undefined is not an object (evaluating 'resetAction.actions.map')`

This works perfectly in demo expo app in Readme but doesn't works when installed locally.

**Comment by mcnamee** [comment]
Hi @pranavpr 
This was a massive time sync for me yesterday on a personal project... 😢

The error is with React Native Router Flux - [see here](https://github.com/aksonov/react-native-router-flux/issues/2799).

You can either use something other than `reset` as the scene type or try downgrading as they suggested (although I found it did not work correctly).

I'll close this as it's related to RNRF - but they've got a big community so I'm expecting they'll fix it soon enough.
