### ISSUE TITLE
Favorites?

### ISSUE THREAD

**Issue by riemers** [mcnamee/react-native-starter-kit#138]
I see favorites being used in the app partially (well favourites), but in the demo there are no options to mark an item as favorite (assuming that is the use case) or am i missing something?

Nice starter kit though, one of the few that does shared web/app which is nice.

**Comment by mcnamee** [comment]
You're correct. There are left over favourites actions from the previous version of the project - I kept them there with the intention to come back and hook them up, but haven't had a spare moment yet.

Feel free to submit a pull request to finish off the functionality

**Comment by riemers** [comment]
Just learning react with firebase, did notice some small things. If i have the time i'll do a PR for things i can fix but i'am still wet behind the ears. (like only being able to select login as text, not the bar) thanks for the nice starter kit though. Most examples never show you the Web/Ios/Android combo.
