### ISSUE TITLE
Your project is started with a tab view , How can i change it to a login screen 

### ISSUE THREAD

**Issue by antosmaman** [mcnamee/react-native-starter-kit#142]
Your project is started with a tab view , How can i change it to a login screen and i don't need a tab view i need to add a plain page after login. Kindly solve my problem.

**Comment by mixcas** [comment]
You can check her how I'm doing it
https://github.com/interglobalvision/app-andamiaje-co/blob/dev/src/native/routes/index.js

**Comment by mcnamee** [comment]
Nice one @mixcas
