### ISSUE TITLE
setTimeout Warning

### ISSUE THREAD

**Issue by cxrod** [mcnamee/react-native-starter-kit#143]
Hi, I just cloned, installed, started and executed this project, and I received the setTimeout warning on my Android 7.1.

I searched in the whole project for the setTimeout and is only used in the logout. I commented this line and the warning continuous showing up, so the problem is not there.

The warning say: Setting a timer for a long period of time, i.e. multiple minutes, is a performace and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. (Saw setTimeout with duration 143614ms)

**Comment by mcnamee** [comment]
@dv297 is correct. This is a long standing issue from Firebase.

https://github.com/mcnamee/react-native-starter-kit/issues/84
