### ISSUE TITLE
Feature request: Flow (or Typescript) support

### ISSUE THREAD

**Issue by yakuzaaaa** [mcnamee/react-native-starter-kit#144]
### Feature: TypeScript support

As react recommends static type checking, typescript support in this starter would be awesome

**Comment by mcnamee** [comment]
Hi @yakuzaaaa 
I think I'd lean toward [Flow](https://flow.org/en/docs/react/) for type checking to keep within the React ecosystem.

If you're able to dig in, I'd love for you to submit a pull request with Flow implemented. Let us know if you're willing to work on it.

**Comment by yakuzaaaa** [comment]
Hi @mcnamee,
I will try to send a PR once my deadlines are over :-)
