### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by shic** [mcnamee/react-native-starter-kit#147]
This project not considered internationalization?

What do you think if we add the following lib?
https://github.com/yahoo/react-intl 

If Ok, I will modify the code and make a PR.

Maybe for RN we need add react-native-i18n... 
What do you think?

**Comment by mcnamee** [comment]
Hi @shic - I'm keen to see your ideas.

Given this is a boilerplate - I'd prefer overall to keep it as lightweight as possible. A light implementation which introduces and allows a new user to start with internationalisation would be ideal, without the bulk that 'requires' the user to use internationalisation.

Hope that makes sense. Thanks for the suggestion!

**Comment by shic** [comment]
@mcnamee 
1. I think we can keep the boilerplate lightweight even we add internationalisation. 
2. Almost all boilerplate I've seen has internationalisation included.
3. A boilerplate should be ready to use for small projects, better not to leave user to implement it. (Maybe users are still unable to do it without learning deeply this boilerplate)

**Comment by mcnamee** [comment]
Thanks @shic - looking forward to seeing what you come up with 👍

**Comment by ahromyak** [comment]
up vote for internationalization

**Comment by shic** [comment]
@mcnamee I tried to add internationalization, could you check it out?

PS: Tried to get language saved in redux state from file `i18n.js`, but can not find a good way? @everyone Some suggestions?

**Comment by shic** [comment]
Hi @mcnamee , I am glad you like my implementation. I will keep working on it.

For me, the translation key should be lower case. 

```
export default {
  Login: 'Login',
  Email: 'Email',
  Password: 'Password',
};
```

Should be 

```
export default {
  login: 'Login',
  email: 'Email',
  password: 'Password',
};
```

Other libs are using lower case, so it's easier to reuse translation texts from other projects.

What do you think?

**Comment by mcnamee** [comment]
How would you suggest handling phrases? Eg. 'Input your email to reset your password'?

**Comment by shic** [comment]
@mcnamee reset_password_msg ? 
Eg. 'Reset password email sent, please check your email.' : reset_password_success_msg

Any suggestion?

**Comment by mcnamee** [comment]
Hi @shic Yep, I like it - great suggestion.
Let's move forward with that 💯

**Comment by shic** [comment]
Hi @mcnamee, I am still working on internationalization. 

I found with your implementation of internationalization, we should pass 'locale' to every container, which is redundant. (I thought about this way before I add internationalization)
Eg: {translate('Password', locale)}

For this reason, I asked :

How to get language saved in redux state from file i18n.js? 

If we can achieve this, we do not need to pass 'locale' every time. What do you think? Any suggestions?

**Comment by mcnamee** [comment]
Hi @shic 
The locale is stored in Redux, therefore accessing redux is required to read the locale.
If you have a better suggestion, I'd love to hear...

**Comment by shic** [comment]
Hi @mcnamee 
Is there a  way to access Redux store outside components ? (Even the 'hacking' way is ok ) I tried to take redux states by import `persistor` and  `store `, but with no luck.

Tried to search on Google, but found nothing...
