### ISSUE TITLE
Unexpected key "recipes" found in previous state received by the reducer

### ISSUE THREAD

**Issue by gitsuraj** [mcnamee/react-native-starter-kit#154]
Hi @mcnamee, I am currently following up this starter kit and trying to customize as necessary. I have removed all instances of recipes from action as well as reducer but I am getting this error when ever I try dispatch any action. I have attached complete error in following screenshot.

[https://ibb.co/giRKzx](url)

**Comment by mcnamee** [comment]
Hi @gitsuraj 
Can you please try flushing your app's Async Storage (_React Native Debugger_ has a function you can click to clear it, otherwise simply delete the app and rebuild)?

If that doesn't work - please do a search on your repo to double check there's definitely no `recipe` string found.

**Comment by gitsuraj** [comment]
It was cache issue. Thanks
