### ISSUE TITLE
how to bundle for IOS device

### ISSUE THREAD

**Issue by jbarros35** [mcnamee/react-native-starter-kit#155]
### Help us reproduce - tell us about your environment

1. Mac High Sierra
2. node is installed and can run it inside a simulator to IOS
3. I can run it inside my phone but need a bundle installation.

### Steps to reproduce

1. I can't find the iOS folder, how do I bundle with xcode 9 and swift?

### Expected result

1. Most tutorials follows about some strange iOS path, that template won't contain it.

Tell me, how can I open the project on my Xcode there is some command to generate the bundle? I only can run the app when reactive localhost is running, I want to run it inside my iPhone for showing my friends about that incredible work.

Regards

**Comment by mcnamee** [comment]
Hi @jbarros35 
Information can be found in the [Expo docs](https://docs.expo.io/versions/latest/distribution/building-standalone-apps).
