### ISSUE TITLE
Clarifications needed on the use of 'Layout'

### ISSUE THREAD

**Issue by amak07** [mcnamee/react-native-starter-kit#156]
@mcnamee Can you please explain how you are connecting to Container components from the native side? I see 'Layout' is being used as part of the flux-router configuration but where is this input defined and how does it connect, say, Recipes Component with Recipes Container?

Also, where is the 'Layout' component coming from ? We see that every container is returning Layout with props attached...

Thanks for clarifications.
Abel

**Comment by jbarros35** [comment]
I'm on the same boat, I did exactly how on recipe thing but didn't worked.

**Comment by mcnamee** [comment]
Hi @amak07 
The project aims to follow the Redux/React concept - [presentational vs container components](https://redux.js.org/basics/usage-with-react#presentational-and-container-components).

A _Container_ will do all the business logic, fetch and data etc and pass props (incl. data) to the Presentational component (which I've just referred to as the _Layout_).

Each screen that you can visit, is setup by a route (eg. [/native/routes](https://github.com/mcnamee/react-native-starter-kit/tree/master/src/native/routes)). This is where we define which container and which layout a screen uses.

To make the cross-platform magic happen, both web and native share containers - in the aim that the business logic is shared and then we can just layout each platform's look and feel according to the platform (eg. the website will look like this and the app will look like that).

Hope that make sense

**Comment by jbarros35** [comment]
After some while reviewing it makes sense. Thanks
