### ISSUE TITLE
How can we link libraries in this project

### ISSUE THREAD

**Issue by gitsuraj** [mcnamee/react-native-starter-kit#158]
What might be the appropriate command equivalent to react-native link react-native-maps

I am trying to integrate react-native-maps in this project which involves linking so what might be best solutions for me to link these library to project.

**Comment by mcnamee** [comment]
Please review the [Expo documentation](https://docs.expo.io/) for help with that. I believe you'd need to eject from Expo.

FYI Expo has it's own version of React-Native-Maps you could check out before ejecting
