### ISSUE TITLE
Double navBar if 'hideNavBar' is false

### ISSUE THREAD

**Issue by paritosh-yadav** [mcnamee/react-native-starter-kit#159]
### Steps to reproduce

1. Just put 'hideNavBar' as false in 'login' scene.

### Expected result

1. Only one navBar should be visible.

### Actual result

1. But two nabBar shows

![screenshot_1524054723](https://user-images.githubusercontent.com/29055750/38932255-47428d42-4333-11e8-9be3-d283a6c9ed63.png)

code here
<img width="1131" alt="screen shot 2018-04-18 at 6 02 13 pm" src="https://user-images.githubusercontent.com/29055750/38932309-70831582-4333-11e8-92e3-94743da6d58a.png">

**Comment by mcnamee** [comment]
I can't see 100% of the code, but is the `Dashboard` scene nested in another stack/scene, and therefore you've got a navbar in the parent and a navbar on dashboard?

**Comment by paritosh-yadav** [comment]
It is just nested under 'stack' (same as login), PFB the code
<img width="1131" alt="screen shot 2018-04-19 at 4 37 13 pm" src="https://user-images.githubusercontent.com/29055750/38988345-75c4458a-43f0-11e8-8c1d-02f385f6ec33.png">

**Comment by mcnamee** [comment]
Hi @paritosh-yadav 
In the latest screenshot you have `hideNavBar` uncommented (in the first you had it commented out) - meaning there should be no navBar according to the latest code.

I can't replicate on my end - it's always doing what it's told for me. I'd suggest opening an issue on the Router's repo if the issue has continued.
