### ISSUE TITLE
 Unable to resolve module `./styles/style.sass` 

### ISSUE THREAD

**Issue by caciobanita** [mcnamee/react-native-starter-kit#164]
### Help us reproduce - tell us about your environment

1. Windows 10, Android *

### Steps to reproduce

1. react-native run-android

### Expected result

1. The native version working well.

### Actual result

1. [Screenshot, logs]
I have structured the an  existing web application like your git project, and is working. I have run react-native upgrade to generate ios and andoid folder, and create the native folder in src, if i run react-native run-android i get  Unable to resolve module `./styles/style.sass`. The require('./styles/style.sass') is in folder web/index.js. Any sugeston for this, i have mising someting in the configuration?

**Comment by mcnamee** [comment]
From what I understand:

- You're working on a separate project and you've tried to reproduce some of the concepts from this repo (i.e. you're not using the code _as is_ from this repo)
- You're trying to run on Android
- When running `react-native run-android` in your project, you get an error about a sass file

Without knowing anything about your project, it sounds like you're requiring a sass file from your one of your native files.

Please let me know if I've understood correctly - as that isn't an _issue_ with this project. Feel free to contact me separately and I'll offer my consulting rates.
