### ISSUE TITLE
Its failing on npm start after the merge done to master

### ISSUE THREAD

**Issue by dynamicsingh** [mcnamee/react-native-starter-kit#166]
react-native-starter-kit/rndebugger:/set-debugger-loc?host=localhost&port=19001 does not exist.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnsk@0.1.0 debug: `open 'rndebugger://set-debugger-loc?host=localhost&port=19001'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rnsk@0.1.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bhupindersingh/.npm/_logs/2018-05-02T17_10_59_424Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnsk@0.1.0 start: `npm run debug && react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rnsk@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

@mcnamee please check and fix. Thanks. Its not able to find a file, removing "npm run debug" from start script in package.json fixes this.

**Comment by mcnamee** [comment]
Can you please fill in the issue template correctly - your environment, steps to reproduce, expected result etc

**Comment by stefanwuthrich** [comment]
I have same problem with fresh clone

Env: Arch Linux, Node 10, NPM 5.6, expo 
Steps: clone, npm i, npm start
Expected Result: open app via expo
Getting: 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnsk@0.1.0 debug: open 'rndebugger://set-debugger-loc?host=localhost&port=19001'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rnsk@0.1.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/bhupindersingh/.npm/_logs/2018-05-02T17_10_59_424Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnsk@0.1.0 start: npm run debug && react-native-scripts start
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rnsk@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by stefanwuthrich** [comment]
ok, it's clear for me. rndebugger cannot be used on Linux: (https://github.com/jhen0409/react-native-debugger/blob/master/docs/getting-started.md)
So I removed the part npm run debug && and it works

**Comment by mcnamee** [comment]
Ah ha, good shout @stefanwuthrich 

I'd added it as a developer convenience (it's a great tool!) knowing that it was cross platform. But I didn't realise that the CLI wasn't consistent across platforms.

I'll remove it

**Comment by dynamicsingh** [comment]
It failed for me on macOS. Can someone try running on macOS, node V8, npm 5.5.1. Can we mention ideal requirement for running it perfectly @mcnamee

**Comment by mcnamee** [comment]
Please supply some more details @dynamicsingh - now that you've tried removing [run debug from the start script](https://github.com/mcnamee/react-native-starter-kit/commit/3462131c43ad74cb39cec16d851db52c677f417b) (or simply cloned from master branch) - what error are you getting?
