### ISSUE TITLE
it is showing error message 

### ISSUE THREAD

**Issue by v4rshith** [mcnamee/react-native-starter-kit#168]
while using react-native run-android command it is showing error message
### Help us reproduce - tell us about your environment

1.windows

### Steps to reproduce

1.

### Expected result

1.

### Actual result

1. [Screenshot, logs]
![error](https://user-images.githubusercontent.com/37027280/39872311-34ad562c-5485-11e8-91c7-af3c3e15c842.PNG)

**Comment by mcnamee** [comment]
Please follow the [Getting Started instructions](https://github.com/mcnamee/react-native-starter-kit#-getting-started).

Specifically, this is a [Create React Native App](https://github.com/react-community/create-react-native-app) so you use `npm start` not `react-native run-android`
