### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by Hcinet** [mcnamee/react-native-starter-kit#169]
> rnsk@0.1.0 debug C:\Users\medam\react-native-starter-kit
> open 'rndebugger://set-debugger-loc?host=localhost&port=19001'

'open' is not recognized as an internal or external command,
operable program or batch file.
'port' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnsk@0.1.0 debug: `open 'rndebugger://set-debugger-loc?host=localhost&port=19001'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rnsk@0.1.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\medam\AppData\Roaming\npm-cache\_logs\2018-05-12T01_42_29_899Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnsk@0.1.0 start: `npm run debug && react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rnsk@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\medam\AppData\Roaming\npm-cache\_logs\2018-05-12T01_42_30_016Z-debug.log

**Comment by speterson-riskalyze** [comment]
I just removed the `npm run debug &&` from the start script in the package.json. Also had to install watchman via homebrew `brew install watchman`

**Comment by mcnamee** [comment]
Thanks @speterson-riskalyze 

(Same as https://github.com/mcnamee/react-native-starter-kit/issues/166)
