### ISSUE TITLE
Cannot debug with breakpoints in VS Code

### ISSUE THREAD

**Issue by 333f1t51b21c1p69mf86ctw611258** [mcnamee/react-native-starter-kit#171]
### Help us reproduce - tell us about your environment

1. I think this issue exists in all environments

### Steps to reproduce

1. Cannot debug with breakpoints in VS Code
I configured launch.json as below and launch webpack-dev-server at the first and launch chrome after that.
2. VS Code ignores all breakpoints

### References 

1. [Screenshot, logs]
<img width="669" alt="screen shot 2018-05-16 at 11 21 05 am" src="https://user-images.githubusercontent.com/7751932/40096572-a3ae6690-58fb-11e8-948a-f3b2496f9183.png">

**Comment by mcnamee** [comment]
Sorry no one has been able to offer any advice on this one. I'll close it due to inactivity.
