### ISSUE TITLE
failed to install grpc on npm install

### ISSUE THREAD

**Issue by suphero** [mcnamee/react-native-starter-kit#175]
I cannot successfully install npm packages on my computer.
 
### Help us reproduce - tell us about your environment

1. macOS 10.13.5
2. npm 6.1.0
3. latest master version

### Steps to reproduce

1. npm i

### Actual result

<img width="830" alt="screen shot 2018-06-17 at 19 51 34" src="https://user-images.githubusercontent.com/846531/41510136-e274efc2-7267-11e8-8629-f01d52af9cdb.png">

Note: This problem occurs because of using older version of firebase. When I update firebase to latest version, authentication acts inconsistently. I think firebase.auth responses changed and authentication related methods should be changed.

**Comment by mcnamee** [comment]
Thanks for the info @suphero 
Would you be able to submit a PR to update/fix this?

**Comment by mcnamee** [comment]
I've updated the dependencies and the new new Firebase API. Should work now.

Let me know if you have any further issues
