### ISSUE TITLE
Redux Storage makes development unmbarable.

### ISSUE THREAD

**Issue by IvRRimum** [mcnamee/react-native-starter-kit#176]
So basically even if i change Firebase child url, the redux storage will still show the old data unless you literary go to the storage config and add it to blacklist(even that sometimes doesn't work).

Is there a way you can disable that while in development?

I believe other devs will encourage the same issue, this is a good issue to bounce a lot of issues/questions.

**Comment by IvRRimum** [comment]
Guys, this is ridiculous... Why the hell would you need an active store cacher in development mode??

How do you even do development?

**Comment by mcnamee** [comment]
@IvRRimum judging by your tone, do you feel that you're paying too much for this code?

This is a question you could check on/raise with [redux-persist](https://github.com/rt2zz/redux-persist). If the feature exists with Redux Persist or you have a way to implement, submit a PR. Whilst I haven't experienced this as an issue for projects I've been involved in, I can see that it'd be a good feature to turn on/off.

**Comment by IvRRimum** [comment]
@mcnamee Sorry, got really frustrated, other than this, this is a really good starter kit.

I will try to implement it and make PR, Hopefully later this week.
