### ISSUE TITLE
Unable to npm install on macOS High Sierra ( 10.13.5)

### ISSUE THREAD

**Issue by mchepuri** [mcnamee/react-native-starter-kit#177]
Unable to install and run on macOS High Sierra ( 10.13.5)
### Help us reproduce - tell us about your environment

I am running in to various installation issues after cloning to my macOS High Sierra ( 10.13.5) and when i tried npm install

1.
macOS High Sierra ( 10.13.5)
### Steps to reproduce

1.git clone https://github.com/mcnamee/react-native-starter-kit.git
2.cd react-native-starter-kit/
3.npm install
### Expected result

1. Application should get installed succesfully

### Actual result

Failed with error as shown in below screen shot
1. [Screenshot, logs]
<img width="1678" alt="screen shot 2018-07-03 at 5 40 06 am" src="https://user-images.githubusercontent.com/33533809/42220445-d11dcd16-7e83-11e8-8f18-0747daff145b.png">

**Comment by mcnamee** [comment]
Can you please try creating a [fresh React Native project](https://facebook.github.io/react-native/docs/getting-started) to rule out whether it's environment related? There errors appear to indicate that there's problems with npm downloading dependencies.

**Comment by mcnamee** [comment]
I believe this issue is fixed alongside https://github.com/mcnamee/react-native-starter-kit/issues/175
