### ISSUE TITLE
Cant debug with react native debugger.

### ISSUE THREAD

**Issue by beratuslu** [mcnamee/react-native-starter-kit#180]
Hello everyone, 

I am starting project as instructed in the readme file. I integrated my firebase with app when I signup it stucks at spinner... though saves email and password to firebase and it signs in without problem. I want to debug whats going on when I hit the signup button but it doesnt show any action etc nor in the react native debugger app. Why react native debugger cant connect to my app. How can I fix this issue?

![image](https://user-images.githubusercontent.com/94031/43021254-a68ee1ca-8c6b-11e8-9a35-16ad4a659134.png)

![image](https://user-images.githubusercontent.com/94031/43021296-d25af1f4-8c6b-11e8-8db8-b2e496e00fd6.png)

**Comment by mcnamee** [comment]
Hi @beratuslu - It looks like you've got 2 debuggers open. You can only have one or the other.
Try closing everything (including the packager, simulators etc), open React Native Debugger first, then `npm start`

**Comment by beratuslu** [comment]
@mcnamee I still cant see which action fires with which data. Why is that?

**Comment by Richacinas** [comment]
I'm experiencing the same issue.

Not sure if I can run the react native debugger while running this starter kit on my phone, or if I need an Andoid Studio virtual device and then I can debug in there.

I follow the steps but the debugger keeps waiting without anything connecting. What port should I open the debugger on?

THanks
