### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by SaintEmbers** [mcnamee/react-native-starter-kit#181]
Wondering if there is any documentation or help with integrating push notifications.  Thanks!
### Help us reproduce - tell us about your environment

1.

### Steps to reproduce

1.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by mcnamee** [comment]
You could try the [Expo docs](https://docs.expo.io/versions/latest/guides/push-notifications.html)
