### ISSUE TITLE
Unable to Signup

### ISSUE THREAD

**Issue by anarayn** [mcnamee/react-native-starter-kit#183]
When I try to signup it doesn't work. When I checked in developer tools it shows below error
Uncaught ReferenceError: regeneratorRuntime is not defined
    at bundle.js:1
    at bundle.js:1
    at Object.onFormSubmit (bundle.js:1)
    at t.n.handleSubmit (bundle.js:1)
    at Object.<anonymous> (bundle.js:1)
    at Object.invokeGuardedCallback (bundle.js:1)
    at Object.invokeGuardedCallbackAndCatchFirstError (bundle.js:1)
    at S (bundle.js:1)
    at P (bundle.js:1)
    at D (bundle.js:1)

### Help us reproduce - tell us about your environment

1. I am trying web version in chrome browser using the link given in README. https://react-boilerplate.mcnam.ee/sign-up

### Steps to reproduce

1. Navigate to https://react-boilerplate.mcnam.ee/sign-up
2. Fill details and try to signup.

### Expected result

1. It should allow me to signup or show error. Currently, it doesn't respond If I press signup.

### Actual result

1. [Screenshot, logs]
![screen shot 2018-08-15 at 1 55 19 pm](https://user-images.githubusercontent.com/6311749/44147119-fb667ca4-a092-11e8-940b-3a4508c8c384.png)

**Comment by mcnamee** [comment]
Hi there @anarayn 
This one was fixed with https://github.com/mcnamee/react-native-starter-kit/pull/185
