### ISSUE TITLE
Image Path

### ISSUE THREAD

**Issue by DaBlitzStein** [mcnamee/react-native-starter-kit#189]
The folder "images" is provided to contain images common on native and react.
Webpack files doesn't consider images inside.

Even if I include images inside webpack, the output path is related below "web" and it cannot use common image folder. 

### Help us reproduce - tell us about your environment

Standar git cloned repository

### Steps to reproduce

Try to include an imagen on any file from the directory src/images in the web version.

### Expected result
Image appears
### Actual result
Image not found.

**Comment by brainahdev** [comment]
Try this:
--------
npm install url-loader

and in web.pack config (dev and prod) add the following under module->loaders
---
{
	test: /\.(png|jpg)$/,
	loader: 'url-loader'
},
---
Then in your file you can load those images as 

---
<img alt="" src={require("../../images/ofoslogo.png")}/>
---

even for me the same issue and resolved like this. It works fine for me.

**Comment by brainahdev** [comment]
Try this:

npm install url-loader

then add this url-loader that helps to load images within app

like

{
	test: /\.(png|jpg)$/,
	loader: 'url-loader'
 },

restart the npm and now you can access the images folder as:

<img alt="" src={require("../../images/oflogo.png")} }/>

**Comment by brainahdev** [comment]
Try this:

**Comment by brainahdev** [comment]
try this:

**Comment by brainahdev** [comment]
let me know if that works

**Comment by risingtalent22** [comment]
It works fine

**Comment by csmtcy** [comment]
@brainahdev the solution is working. Thanks !
