### ISSUE TITLE
Example jest testing fails out of the box

### ISSUE THREAD

**Issue by j-funk** [mcnamee/react-native-starter-kit#190]
When I run `npm test` after installing the example test in `App.test.js` is discovered and fails. 

I'm running OSX 10.13.6, npm 6.4.1, node 10.11.0

### Steps to reproduce
1. Go to root directory in terminal and run `npm test`, select `a` option to run all tests from the command line prompt

### Expected result
Tests should run and pass.

### Actual result
The test is discovered and fails:
```
  ● Test suite failed to run

    /Users/jfunk/Documents/Code/git/RN-PVP/node_modules/redux-persist/es/integration/react.js:9
    import React, { PureComponent } from 'react'; // eslint-disable-line import/no-unresolved
           ^^^^^

    SyntaxError: Unexpected identifier

      4 | import { Provider } from 'react-redux';
      5 | import { Router, Stack } from 'react-native-router-flux';
    > 6 | import { PersistGate } from 'redux-persist/es/integration/react';
        | ^
      7 |
      8 | import { Root, StyleProvider } from 'native-base';
      9 | import getTheme from '../../native-base-theme/components';

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/native/index.js:6:1)

Test Suites: 1 failed, 1 total
```

**Comment by nimrod-cohen** [comment]
same issue for me, did you happen to resolve?

**Comment by JamesGelok** [comment]
Why would it fail on the 6th import statement?
```
    > 6 | import { PersistGate } from 'redux-persist/es/integration/react';
        | ^
```
It looks like it's the first import statement that navigates within node_modules. 
So this smells like a babel + jest config issue but I'm not sure

**Comment by JamesGelok** [comment]
Actually, I think this is the issue. Unable to work on it now, but this looks like precisely what's going wrong:
https://stackoverflow.com/questions/48056631/syntaxerror-unexpected-token-import-with-jest/48056912#48056912

**Comment by j-funk** [comment]
I eventually worked around this with:

  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": []
  },

From [this issue](https://github.com/expo/sentry-expo/issues/12).

**Comment by j-funk** [comment]
Also add `jest.useFakeTimers();` to the test file.

```
import React from 'react';
import renderer from 'react-test-renderer';
import App from './App';

jest.useFakeTimers();

it('renders without crashing', () => {
  const rendered = renderer.create(<App />).toJSON();
  expect(rendered).toBeTruthy();
});
```
