### ISSUE TITLE
Remove gulp?

### ISSUE THREAD

**Issue by davesnx** [mcnamee/react-native-starter-kit#195]
Hello @mcnamee 

A first-timer React Native here, I just cloned this repo and made it a little bit my own and I discovered a few things that can be improved. 

First, I would recommend removing gulp dependency in order to just keep the script that "Clears react-packager cache". 

Thanks for the hard-work on this boilerplate.

**Comment by mcnamee** [comment]
Sounds great @davesnx - would you mind submitting a PR?
