### ISSUE TITLE
Avoid commiting build folder into upstream

### ISSUE THREAD

**Issue by davesnx** [mcnamee/react-native-starter-kit#196]
Hey @mcnamee,

It's me again, another small improvement here:

You don't need to commit the build folder neither have the bash script. I would recommend to use `gh-pages` as CLI and previously run the build.

The same way as CRA have documented to Deploy their app to Github Pages: https://facebook.github.io/create-react-app/docs/deployment#step-2-install-gh-pages-and-add-deploy-to-scripts-in-packagejson

**Comment by mcnamee** [comment]
Looks like a great option, thanks @davesnx
