### ISSUE TITLE
Not found fontFamily Ionicons

### ISSUE THREAD

**Issue by juanagu** [mcnamee/react-native-starter-kit#197]
When execute the app using yarn start and then selected iOS or Android this error appeared (Only when I rename the root folder "react-native-starter-kit" works fine with name react-native-starter-kit) 

fontFamily 'Ionicons' is not a system font and has not been loaded through Expo.Font.loadAsync.
- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
- If this is a custom font, be sure to load it with Expo.Font.loadAsync.
- node_modules/expo/src/Font.js:33:10 in processFontFamily
- ... 31 more stack frames from framework internals

### Help us reproduce - tell us about your environment

1. Mac
2. Android or iOS
3. Latest version from master. Download zip.

### Steps to reproduce

1. run yarn install
2. run yarn start
3. press "i" or "a"

### Expected result

1. show app icons

### Actual result

1. 

<img width="377" alt="screen shot 2018-11-06 at 12 18 40" src="https://user-images.githubusercontent.com/4689126/48073734-207e8b00-e1be-11e8-952f-b73308cd4dbd.png">
<img width="376" alt="screen shot 2018-11-06 at 12 18 46" src="https://user-images.githubusercontent.com/4689126/48073739-22e0e500-e1be-11e8-9d0f-4a27a63b5e24.png">

2. Log

> fontFamily 'Ionicons' is not a system font and has not been loaded through Expo.Font.loadAsync.
> - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
> - If this is a custom font, be sure to load it with Expo.Font.loadAsync.
> - node_modules/expo/src/Font.js:33:10 in processFontFamily
> - ... 31 more stack frames from framework internals

**Comment by daichuqi** [comment]
I had the exact same issue. only renaming back to react-native-starter-kit works which seems super strange.

**Comment by pdubey84** [comment]
You need to do this in your index.js... You might have to change it to a react class

`componentWillMount() {
    this.loadFonts();
  }
  async loadFonts() {
    await Expo.Font.loadAsync({
      Roboto: require("native-base/Fonts/Roboto.ttf"),
      Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
      Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf")
    });
  }`

**Comment by mcnamee** [comment]
I've added something similar into the repo on master branch - let me know if it doesn't solve the issue, and I'll re-open.

https://github.com/mcnamee/react-native-starter-kit/commit/7494bda1f53c56acfd86087ecac6f39f8bb540a9
