### ISSUE TITLE
React native demo - login page crashing in Expo

### ISSUE THREAD

**Issue by tweetzal** [mcnamee/react-native-starter-kit#201]
### Help us reproduce - tell us about your environment

1.

### Steps to reproduce

1.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by tweetzal** [comment]
HI React native expo demo crashes when using QR code to testing app by logging in

**Comment by mcnamee** [comment]
Hi @tweetzal 
Thanks for passing on your feedback.

Does the issue happen when you clone, install and run locally? I've tested and can't reproduce. I'll close for now, but let me know and I'll reopen if necessary
