### ISSUE TITLE
'react' peer dependency missing

### ISSUE THREAD

**Issue by raphaelbadia** [mcnamee/react-native-starter-kit#204]
Hello, I just cloned the repository and launched the app

The app started but I got the following error messages:
> 17:14:47: Warning: 'react' peer dependency missing. Run `npm ls` in /private/tmp/react-native-starter-kit to see full warning.
> 17:14:47: Warning: 'react-native' peer dependency missing. Run `npm ls` in /private/tmp/react-native-starter-kit to see full warning.
> 17:14:47:
> 17:14:47: If there is an issue running your project, please run `npm install` in /private/tmp/react-native-starter-kit and restart.

### Help us reproduce - tell us about your environment

1. Mac
2. ios
3. latest version from git clone

### Steps to reproduce

1. clone the repository
2. cd repo_name
3. `yarn install`
4. launch the debugger
5.  `yarn start`

### Expected result

No error message

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/1901628/49165810-584a9f80-f332-11e8-8418-9594e4478356.png)

**Comment by cdurth** [comment]
mine is doing this as well, Windows 10, Android.

I can usually get it to go away after a couple restarts, if not i re-run npm install. really annoying tho as it slows me down

**Comment by mcnamee** [comment]
@raphaelbadia What you're seeing are just warnings - nothing to be too concerned about.

I have just updated most of the dependencies in master branch.

Please note that Expo generally runs a React Native version a few behind latest, meaning the React dependency for this repo, unfortunately also needs to be behind.

**Comment by raphaelbadia** [comment]
Thanks !
