### ISSUE TITLE
Question: How to handle SEO?

### ISSUE THREAD

**Issue by rrjanbiah** [mcnamee/react-native-starter-kit#209]
Looks very nice. But, how to handle SEO? Are there any known approaches? TIA

**Comment by mcnamee** [comment]
Hi @rrjanbiah 
Unfortunately I'm not an authority on SEO. However I'd probably recommend looking at [NextJS](https://github.com/zeit/next.js/) for server side rendering, which may assist with SEO.

**Comment by rrjanbiah** [comment]
@mcnamee Thank you
