### ISSUE TITLE
Question: Comparison with ReactXP

### ISSUE THREAD

**Issue by rrjanbiah** [mcnamee/react-native-starter-kit#210]
If I'm right, both the libraries help targeting multiple platform. If so, are there any comparison on when to choose one? TIA

**Comment by mcnamee** [comment]
Hi @rrjanbiah 
I haven't used ReactXP to comment on that. But [have a read of this](https://github.com/mcnamee/react-native-starter-kit/blob/master/docs/faqs.md#is-this-a-universal-app) to understand what this repo does, which may help you understand the differences

**Comment by rrjanbiah** [comment]
@mcnamee Thank you
