### ISSUE TITLE
Any Plans to support Storybook?

### ISSUE THREAD

**Issue by wlee367** [mcnamee/react-native-starter-kit#212]
Hi there, this is a really nice library, very painless to set up. I was wondering if you have any plans to support Storybook out of the box in a future version of the library? 

I myself will be attempting to implement storybook in to my project using this boilerplate. I'll report back here if it has been successful for me. 

### Help us reproduce - tell us about your environment

1.

### Steps to reproduce

1.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by mcnamee** [comment]
No plans, but would be happy to see what you come up with.
