### ISSUE TITLE
Unable to start the react web app

### ISSUE THREAD

**Issue by uimax** [mcnamee/react-native-starter-kit#213]
I cloned react-native-starter-kit git and follow the instructions: `yarn install` and then `yarn run web`, but web app not working. I have received the error as shown below:

![5053308b092333b800ad53aeb53a0176](https://user-images.githubusercontent.com/24828168/53281626-47a59c00-375e-11e9-9148-e59199830c7e.png)

And did you remove the webpack?

Thanks!

**Comment by mcnamee** [comment]
Looks to be an error with the variable setting - i.e. `PORT=3001`. Can you try removing that part of the respective `package.json` command and let me know if it resolves?
