### ISSUE TITLE
Converting to Rematch

### ISSUE THREAD

**Issue by ealemda2** [mcnamee/react-native-starter-kit#215]
Has there been any consideration to convert the Redux store in the project to [Rematch](https://github.com/rematch/rematch)?

In my experience this reduces the amount of boilerplate significantly and improves the workflow since it collects  state, reducers, async actions & action creators in a single place (models). I'll be trying it myself and believe it would be helpful especially when using the same store to build both a mobile and a web app.

Thoughts?

Very useful boilerplate, by the way. Thanks!

**Comment by mcnamee** [comment]
Conversation continued over here in the PR: https://github.com/mcnamee/react-native-starter-kit/pull/216
