### ISSUE TITLE
Question: Any interest in putting together a premium version for sale on SugarKubes?

### ISSUE THREAD

**Issue by wrannaman** [mcnamee/react-native-starter-kit#219]
Hi Matt, congrats on the traction! Would you be interested in putting together a premium version of this repo to sell on [SugarKubes](https://sugarkubes.io)? It's a code and container marketplace I'm putting together.

**Comment by mcnamee** [comment]
Thanks @wrannaman - Sounds interesting.

**Comment by wrannaman** [comment]
Cool! Let me know if you'd like to talk I'm at andrew [at] sugarkubes.io.
