### ISSUE TITLE
Installing Expo Client on iOS simulator - not installing app on simulator

### ISSUE THREAD

**Issue by vinh3928** [mcnamee/react-native-starter-kit#225]
### Help us reproduce - tell us about your environment

1. I'm using MacIOS Mojave 10.14.5
2. xcode 10.2.1

### Steps to reproduce

1. Pull down repo
2. yarn install
3. yarn start
4. enter "i" for ios
5. Metro starts up
Starting Metro Bundler on port 19001
Tunnel ready
Downloading the latest version of expo client app
Installing Expo client on iOS simulator
///////
Simulator opens up with the standard app installed but not the react native app installed
### Expected result

1. I think something else should happen as well ? I'm a Newbie to mobile development so I really don't know.

### Actual result

<img width="455" alt="Screen Shot 2019-07-18 at 12 33 39 PM" src="https://user-images.githubusercontent.com/11489013/61482665-6a785d00-a958-11e9-999f-b00a62127346.png">
<img width="462" alt="Screen Shot 2019-07-18 at 12 33 44 PM" src="https://user-images.githubusercontent.com/11489013/61482682-6fd5a780-a958-11e9-9f7f-c17f24c30453.png">

**Comment by mcnamee** [comment]
Should be resolved in PR https://github.com/mcnamee/react-native-starter-kit/commit/0ce8b62f86c47608dac56f5ac668fe6e85eb17e6
