### ISSUE TITLE
whereIn which file you pass member and logout to Profile?

### ISSUE THREAD

**Issue by Ladvace** [mcnamee/react-native-starter-kit#226]
In which file you pass member and logout to Profile ( src>native>Components>User ) t?
![Cattura](https://user-images.githubusercontent.com/31326058/62482182-ccd4b880-b7b4-11e9-8955-df7f8762b4a7.PNG)

**Comment by mcnamee** [comment]
The container (not to be confused with the Bootstrap <Container /> component) passes in props to the Layout component
