### ISSUE TITLE
i am not able to build apk. I am using expo cli.

### ISSUE THREAD

**Issue by jitanshu** [mcnamee/react-native-starter-kit#228]
### Help us reproduce - tell us about your environment

1.

### Steps to reproduce

1.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by indriks** [comment]
Thats because Expo cli has a new version.

**Comment by mcnamee** [comment]
Resolved in PR https://github.com/mcnamee/react-native-starter-kit/commit/0ce8b62f86c47608dac56f5ac668fe6e85eb17e6
