### ISSUE TITLE
expo SDK version is outdated

### ISSUE THREAD

**Issue by fmchan** [mcnamee/react-native-starter-kit#232]
I cannot open the app anymore on the latest expo client 1.13.
The Expo Client supports sdk 33,34,35 only, so the sdk of this project which is 32, is outdated.

would anyone like to suggest the version update for all those dependances in this project?
Thank you.

**Comment by vraithe** [comment]
Same issue as @fmchan

**Comment by serkanbektas** [comment]
@fmchan @vraithe Look at this PR [https://github.com/mcnamee/react-native-starter-kit/pull/233](url)

**Comment by Khmelovsky** [comment]
HI @fmchan , @vraithe , @serkanbektas  Are you solve  this  problem?

**Comment by serkanbektas** [comment]
> HI @fmchan , @vraithe , @serkanbektas Are you solve this problem?
> UPD: Solved. it's needed update sdk to 35.0.0
> 
> `$expo update 35.0.0`

I solved and opened PR.

**Comment by mcnamee** [comment]
Resolved in PR https://github.com/mcnamee/react-native-starter-kit/commit/0ce8b62f86c47608dac56f5ac668fe6e85eb17e6

Thanks @serkanbektas
