### ISSUE TITLE
Need to update Expo demo to latest version

### ISSUE THREAD

**Issue by indriks** [mcnamee/react-native-starter-kit#234]
Demo expo app needs to be updated: https://expo.io/@mcnamee/react-native-starter-kit

**Comment by nhaancs** [comment]
yes, having a problem with expo too
do you know the quick fix @indriks ?

**Comment by indriks** [comment]
After updating expo you have change 3 lines:
In file **/src/native/index.js** change to this:
Line 3 `import * as Font from 'expo-font'`
Line 29 `Roboto: require('../../node_modules/native-base/Fonts/Roboto.ttf'),`
Line 30 `Roboto_medium: require('../../node_modules/native-base/Fonts/Roboto_medium.ttf'),`
Line 31 `Ionicons: require('../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf'),`

**Comment by nhaancs** [comment]
Thanks @indriks, you save my day :D

**Comment by n3rd253** [comment]
@indriks 

After making your changes suggested above, expo now runs the app as you'd expect, however

Finished building JavaScript bundle in 17046ms.
Running application on iPhone 11.

redux-persist failed to create sync storage. falling back to noop storage.
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/redux-persist/es/storage/getStorage.js:34:20 in getStorage
- node_modules/redux-persist/es/storage/createWebStorage.js:3:27 in createWebStorage
- node_modules/redux-persist/es/storage/index.js:2:32 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* src/store/index.js:5:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* App.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:5:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:197:45 in guardedLoadModule
* null:null in global code

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, the componentWillUnmount method,
    in App (at App.js:8)
    in App (at withExpoRoot.js:26)
    in RootErrorBoundary (at withExpoRoot.js:25)
    in ExpoRoot (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in DevAppContainer (at AppContainer.js:112)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:638:36 in warningWithoutStack
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:16356:6 in warnAboutUpdateOnUnmounted
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17937:37 in scheduleWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:6934:17 in enqueueSetState
- node_modules/react/cjs/react.development.js:325:31 in <unknown>
* src/native/index.js:34:18 in componentWillMount$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- ... 13 more stack frames from framework internals

---

Have you also run in to this?

**Comment by indriks** [comment]
@n3rd253 I have not tried to upgrade all dependencies. Have you tried to upgrade one by one to see what causing the problem?

**Comment by codaabraham** [comment]
Now getting this: 
```
Unable to resolve "firebase" from "src/lib/firebase.js"
Failed building JavaScript bundle.
```

**Comment by mcnamee** [comment]
The demo been updated at https://expo.io/@mcnamee/react-native-starter-kit
