### ISSUE TITLE
App crashes in Windows 10

### ISSUE THREAD

**Issue by erhan355** [mcnamee/react-native-starter-kit#244]
Executed npx react-native run-android and app crashed.No error message.

Environment
Windows 10
Npm 6.13.7
![image](https://user-images.githubusercontent.com/14984675/75274151-5dd3b580-5813-11ea-88e8-76c9276cdf9f.png)

λ npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1028 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Task :app:installDebug
09:08:49 V/ddms: execute: running am get-config
09:08:49 V/ddms: execute 'am get-config' on '192.168.33.101:5555' : EOF hit. Read: -1
09:08:49 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Google Nexus 7 - 4.1.1' for app:debug
09:08:49 D/app-debug.apk: Uploading app-debug.apk onto device '192.168.33.101:5555'
09:08:49 D/Device: Uploading file onto device '192.168.33.101:5555'
09:08:49 D/ddms: Reading file permision of C:\Users\Erhan\Desktop\reactStarter\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
09:08:50 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
09:08:54 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on '192.168.33.101:5555' : EOF hit. Read: -1
09:08:54 V/ddms: execute: returning
09:08:54 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
09:08:54 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on '192.168.33.101:5555' : EOF hit. Read: -1
09:08:54 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 16s
135 actionable tasks: 2 executed, 133 up-to-date
info Connecting to the development server...
adb.exe: error: closed
warn Failed to connect to development server using "adb reverse": Command failed: C:\Users\Erhan\AppData\Local\Android\Sdk/platform-tools/adb -s 192.168.33.101:5555 reverse tcp:8081 tcp:8081
info Starting the app on "192.168.33.101:5555"...
Starting: Intent { cmp=com.reactnativestarterkit/.MainActivity }

**Comment by mcnamee** [comment]
Thanks for reporting!

https://github.com/mcnamee/react-native-starter-kit/commit/52e70c366d7b661439fa7dd4c372f06a7a6888e7#diff-dc46f9f5dfe204e394fb41395ccd03cfR182-R183 should fix that

**Comment by erhan355** [comment]
Thank you,It works now.
