### ISSUE TITLE
[Q] Any kinf of configuration available?

### ISSUE THREAD

**Issue by trsh** [mcnamee/react-native-starter-kit#245]
I would like to configure how images are handled. Some are bundled under  /static/media, some are represented as data: links. I think it depends on size. I would like to control this behavior.

**Comment by mcnamee** [comment]
I'm sorry, I'm not sure what you're asking.
Would you mind clarifying what the issue is?

**Comment by trsh** [comment]
@mcnamee so if I do this on WEB side:

```
import x from '../../../images/cards-white-fill/y.png';
import x1 from '../../../images/cards-white-fill/y1.png';
...
<Media src={x} />
<Media src={x1} />
```

and then check the source of rendered dom. The links are <img src="/static/media/y-Q.ae974378.png" /> and <img src="data:image/png;base64,iVBORw....[longcode]" />

So there is some mechanism that decides to serve the image as file or a data string. My problem is that I see no configuration to have control over this process. That in turn prevents me to build any kind of image **pre-loading**, that we need for our project.

**Comment by mcnamee** [comment]
Gotcha. No this project doesn't implement any specific configuration on top of Create React App. However you could find out more by looking at https://github.com/facebook/create-react-app to see if the tool can do what you need
