### ISSUE TITLE
Can't get .env variables working

### ISSUE THREAD

**Issue by trsh** [mcnamee/react-native-starter-kit#246]
I created a`.env` file in root directory and put `IMAGE_INLINE_SIZE_LIMIT=80000` inside, but it's not taken into account. 

Got the instructions from https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env , https://create-react-app.dev/docs/adding-images-fonts-and-files

I start the project with `set HTTPS=true&npm run web`  and deploy with `npm run web-bundle` + `firebase deploy --only hosting`

`"react-scripts": "2.1.8",`

**Comment by mcnamee** [comment]
Hi @trsh This project is a React *Native* project (not a create-react-app ReactJS web project)

**Comment by trsh** [comment]
@mcnamee you are not being here helpful at all! 

a) Last time I asked you about my issue https://github.com/mcnamee/react-native-starter-kit/issues/245 here , you forwarded me to read "Create React App" docs. Why? If it doesn't relate.

b) If `IMAGE_INLINE_SIZE_LIMIT` doesn't work with this package, what does? Instead of just fast closing the issue you could provide a solution.

**Comment by mcnamee** [comment]
Hi @trsh 
That's correct - back then I could see that you were referring to web specific issues (which this project doesn't not target anymore) - so I did a Google search for you to help point you in the right direction.

To be clear - the current code in this repo, is for React Native (not React Web). There is a React (web)-specific version of the repo over here: https://github.com/mcnamee/react-starter-kit
But even so, the issue you've linked to references that it's part of React-Scripts v5 - but that project has React Scripts v3.x. So it's not a compatibility at this stage.

BTW it's a very entitled view, to believe that I have an obligation to provide a you solution. OSS is a volunteer contribution.

**Comment by trsh** [comment]
@mcnamee 

can"react-scripts" set to latest version?? That one doe's support `IMAGE_INLINE_SIZE_LIMIT` in '.env' (tried it my self). But other stuff breaks :(, that am not able to fix.

**Comment by trsh** [comment]
Ouh I see its not even used any more :/
