### ISSUE TITLE
How to change project name and package?

### ISSUE THREAD

**Issue by nguyenrio18** [mcnamee/react-native-starter-kit#249]
Hello,

I have used your template two years ago :)
And this is the second one,
Please let me know how to change the project name and related code.

Thank you.

**Comment by mcnamee** [comment]
Hi @nguyenrio18 😊
You can find how to change the project name here:
https://github.com/mcnamee/react-native-starter-kit/blob/master/documentation/faqs.md#how-do-i-change-the-react-native-app-namebundle-id
