### ISSUE TITLE
r.split is not a function.

### ISSUE THREAD

**Issue by aijason** [mcnamee/react-native-starter-kit#254]
![image](https://user-images.githubusercontent.com/13975853/119075236-0b3b7600-ba23-11eb-8b83-9051b2147c2e.png)

**Comment by aijason** [comment]
When I click the third tab at the bottom, this error will appear

**Comment by TheAlphaRice** [comment]
I was able to fix this by going to node_modules/react-hook-form/dist/index.cjs.js, changing the line (line 32 for me) where it has `r.split(...)` to `r.toString().split(...);`  

This will give you another error in the same file, near line 182.  It'll say that `e.replace(...)` is undefined too.  So just do the same thing there:  `e.toString().replace(...)`.  It'll temporarily fix the issue so you can see the form, but I'm hoping someone has a more permanent fix.

**Comment by PhanNN** [comment]
related to register function
https://react-hook-form.com/api/useform/register

We can use 
`register('email', { required: errorMessages.missingEmail });`
